[package]
name = "tlook"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.1"
ratatui = "0.29.0"
shell-words = "1.1"
